version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - chmod -R +x node_modules/typescript/bin/tsc
      - npm install
  build:
    commands:
      - echo Building application...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
cache:
  paths:
    - 'node_modules/**/*'