version: 0.2
      env:
        variables:
    VITE_API_BASE_URL: "https://dx2px72n79.execute-api.us-east-1.amazonaws.com/dev"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building application...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
cache:
  paths:
    - 'node_modules/**/*'